import Image from "next/image";
import Link from "next/link";

const expertise = [
  { n: "01", title: "Reinsurance placement", text: "Market access and placement strategy aligned to the cedant, exposure and commercial objective." },
  { n: "02", title: "Captive management", text: "A practical Nassau-based hub for captive formation, governance and ongoing company management." },
  { n: "03", title: "Marine risks", text: "Specialist reinsurance thinking for cargo, shipping and the operational chain around maritime trade." },
  { n: "04", title: "Financial & indemnity", text: "Structured responses for credit, contractual, professional and liability-linked exposures." },
];

export default function Home() {
  return <><section className="hero"><Image src="/hero.webp" alt="Modern Nassau waterfront offices at dusk" fill priority sizes="100vw" /><div className="hero-shade" /><div className="container hero-content"><p className="eyebrow light">Nassau · Global markets</p><h1>Risk moves.<br />We move first.</h1><p className="hero-copy">Reinsurance intermediation and company management for complex financial, indemnity and marine exposures.</p><div className="hero-actions"><Link className="button" href="/contact">Partner with us <span>↗</span></Link><Link className="text-link light" href="#expertise">Explore expertise <span>↓</span></Link></div></div><div className="hero-proof"><span>Nassau headquarters</span><span>International reach</span><span>Specialist execution</span></div></section>
  <section className="intro section" id="about"><div className="container split-intro"><div><p className="eyebrow">About Nexus</p><h2>A specialist bridge between risk and capital.</h2></div><div><p className="lead">Nexus Reinsurance Group operates from The Bahamas with an international outlook and a deliberately hands-on model.</p><p>We bring intermediary, management and underwriting perspectives together to help clients navigate sophisticated placement and company-management requirements.</p><Link className="text-link" href="/contact">Speak with the team <span>↗</span></Link></div></div></section>
  <section className="section section-ink" id="expertise"><div className="container"><div className="section-heading inverse"><p className="eyebrow light">Expertise</p><h2>Precision for risks that demand more attention.</h2><p>Independent analysis, specialist market coordination and accountable execution.</p></div><div className="capability-grid">{expertise.map((item)=><article key={item.n}><span>{item.n}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
  <section className="section" id="approach"><div className="container"><div className="section-heading"><p className="eyebrow">How we work</p><h2>Understand the exposure. Build the route. Stay through execution.</h2></div><ol className="process"><li><span>01</span><div><h3>Diagnose</h3><p>Establish the exposure, existing programme, objectives and decision constraints.</p></div></li><li><span>02</span><div><h3>Design</h3><p>Develop a placement or management pathway shaped by regulation, capacity and economics.</p></div></li><li><span>03</span><div><h3>Deliver</h3><p>Coordinate markets, documentation, governance and communication through completion.</p></div></li></ol></div></section>
  <section className="section portfolio-section" id="nassau"><div className="container split-intro"><div><p className="eyebrow">Nassau advantage</p><h2>A respected insurance jurisdiction with global connectivity.</h2></div><div><p className="lead">Our Nassau base supports an international approach to reinsurance intermediation and captive company management.</p><p>Clients benefit from a responsive team, a strong professional-services ecosystem and access to cross-border relationships.</p><div className="contact-details"><p><strong>Global reach</strong><br />Asia · Europe · Americas</p><p><strong>Core disciplines</strong><br />Financial · Indemnity · Marine</p></div></div></div></section>
  <section className="cta-band"><div className="container"><p className="eyebrow light">The next conversation</p><h2>Bring us the risk others reduce to a category.</h2><Link className="button button-light" href="/contact">Partner with Nexus <span>↗</span></Link></div></section></>;
}
